# Generated by Django 2.2.12 on 2023-11-15 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_auto_20231108_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='users',
            new_name='username',
        ),
    ]
